/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p remote_kmail /usr/share/dbus-1/interfaces/org.kde.kmail.kmail.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "remote_kmail.h"

/*
 * Implementation of interface class OrgKdeKmailKmailInterface
 */

OrgKdeKmailKmailInterface::OrgKdeKmailKmailInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeKmailKmailInterface::~OrgKdeKmailKmailInterface()
{
}


#include "remote_kmail.moc"
